name: .NET 8

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Generate NuGet package
      run: |
         cd src\DotNetEd.CoreAdmin
         dotnet pack -c Release -o out
    - name: Setup nuget
      uses: nuget/setup-nuget@d105a947828025cd7a980103c35ba2bfae586d0f # v2.0.2
      with:
        nuget-api-key: ${{ secrets.PACKAGE_PAT }}
    - name: Push generated package to Github
      run: |
         dotnet nuget add source "https://nuget.pkg.github.com/amplified-global/index.json" --name "AmpPackages" --username "amplified-global" --password ${{ secrets.PACKAGE_PAT }} --store-password-in-clear-text
         nuget push src\DotNetEd.CoreAdmin\out\*.nupkg -SkipDuplicate -NoSymbols -Source "AmpPackages"

